### ISSUE TITLE
Audio output? 

### ISSUE THREAD

**Issue by LukasLLL** [Mrugalla/PerlinNoiseMod#2]
Hey, thanks for this plugin. Is there any way to get it to output audio directly? I would like to play the perlin noise with midi, if thats possible?

**Comment by Mrugalla** [comment]
If you turn up the rate as much as possible you start to hear the modulation signal reach audiorate territory. but since it's a procedurally generated strip of audio the repeating pattern becomes too audible at such rates. I'd rather advice you to synthesize white noise with any synthesizer and then use a keytracked lowpass filter to shape something perlin-like into the noise. you could for example try rift filter lite for that
